<a href="https://colab.research.google.com/github/tanujsaini05/CreditCardANN/blob/main/creditCardANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset=pd.read_csv('creditcard.csv')

In [ ]:
dt=dataset.iloc[:1000,:]

In [ ]:
X,y=dt.iloc[:,:-1],dt.iloc[:,-1]

In [ ]:
X

Time        V1        V2        V3        V4        V5        V6  \
0       0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1       0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2       1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3       1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4       2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
..    ...       ...       ...       ...       ...       ...       ...   
995   751 -0.654892  0.608319  1.585102 -3.009429  0.037593 -1.954023   
996   752 -2.101171 -0.227365  1.624668 -0.291123  1.902446 -1.483921   
997   753 -1.248163  0.315246  3.708935  0.687280 -0.873071  1.091287   
998   755  1.374134 -1.767210 -0.433352 -2.229552  0.331135  3.924775   
999   755 -2.497436  1.402769  0.184840 -2.504117 -0.111803 -0.902909   

           V7        V8        V9  ...       V20       V21       V22  \
0    0.239599  0.098698  0.363787  ...  0.251412 -0.018307  0.277838   
1   -0.078803  0.085102 -0.255425  ... -0.069083 -0.225775 -0.638672   
2    0.791461  0.247676 -1.514654  ...  0.524980  0.247998  0.771679   
3    0.237609  0.377436 -1.387024  ... -0.208038 -0.108300  0.005274   
4    0.592941 -0.270533  0.817739  ...  0.408542 -0.009431  0.798278   
..        ...       ...       ...  ...       ...       ...       ...   
995  1.335977 -0.612858  0.690254  ... -0.137097 -0.078527 -0.064194   
996 -0.275117  0.085964 -0.563098  ... -0.134549 -0.313782 -0.804784   
997  0.297707 -0.633135  1.102317  ...  0.593323 -0.824013  0.057907   
998 -2.049947  1.001403 -1.183310  ... -0.068174 -0.252942 -0.461534   
999  0.110183 -3.655788  2.231761  ... -0.417931  2.777155 -0.664909   

          V23       V24       V25       V26       V27       V28  Amount  
0   -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62  
1    0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69  
2    0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3   -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50  
4   -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99  
..        ...       ...       ...       ...       ...       ...     ...  
995 -0.107350  0.961776 -0.067760 -0.549465 -0.232588 -0.108261    3.90  
996 -0.474101  0.008102  0.259725  0.032376  0.323580  0.034622    1.78  
997 -0.282351  0.630774  0.283506 -0.204264  0.097555 -0.670480   30.00  
998 -0.030890  0.997119  0.384299 -0.187538  0.068817  0.038009   82.37  
999  0.594689  0.330380  0.064190 -0.110533  0.672165  0.114739    8.00  

[1000 rows x 30 columns]

In [ ]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
995    0.0
996    0.0
997    0.0
998    0.0
999    0.0
Name: Class, Length: 1000, dtype: float64

In [ ]:
from imblearn.over_sampling import RandomOverSampler

In [ ]:
ros=RandomOverSampler(random_state=42)
X_res,y_res=ros.fit_resample(X,y)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=34)

In [ ]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [ ]:
ss=StandardScaler()

In [ ]:
mms=MinMaxScaler(feature_range=(0,1))

In [ ]:
X_train=ss.fit_transform(X_train)

In [ ]:
#X_train=mms.fit_transform(X_train)
#y_train=mms.fit_transform(y_train)

In [ ]:
X_train

array([[ 0.89290079, -0.45112331,  0.52470742, ...,  0.85687871,
        -0.1897867 , -0.30170228],
       [ 1.27601202,  0.84205971, -0.78719325, ..., -0.13590794,
         0.19690083,  0.24717852],
       [-1.29567714, -0.9553173 ,  0.05334192, ..., -0.31026582,
         0.49341866,  0.06396485],
       ...,
       [-0.04506118,  1.08882556,  0.04363064, ..., -0.11698713,
         0.13993681, -0.34067636],
       [-1.28246641, -0.33723737, -0.16415288, ..., -0.09141292,
        -0.37455282,  0.18463754],
       [-0.29606509, -0.61251767,  1.31425456, ...,  0.69656155,
         0.74045134, -0.29658344]])

In [ ]:
X_train.shape

(700, 30)

In [ ]:
# Starting neural Network

In [ ]:
import tensorflow as tf

In [ ]:
model=tf.keras.Sequential()

In [ ]:
from tensorflow.keras import activations

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(40, activation="relu", input_dim=30))
model.add(tf.keras.layers.Dense(70, activation='relu'))
model.add(tf.keras.layers.Dense(50, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),loss=tf.keras.losses.BinaryCrossentropy(),metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 40)                1240      
                                                                 
 dense_1 (Dense)             (None, 70)                2870      
                                                                 
 dense_2 (Dense)             (None, 50)                3550      
                                                                 
 dense_3 (Dense)             (None, 1)                 51        
                                                                 
Total params: 7,711
Trainable params: 7,711
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
early_stop=tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.0001,
    patience=5,
    verbose=1,
    mode="auto",
    baseline=None,
    restore_best_weights=False,
    start_from_epoch=0,
)

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=20,callbacks=early_stop,batch_size=32)

Epoch 1/20
22/22 [==============================] - 2s 16ms/step - loss: 0.3288 - accuracy: 0.9729 - val_loss: 2.8667e-04 - val_accuracy: 1.0000
Epoch 2/20
22/22 [==============================] - 0s 4ms/step - loss: 0.0683 - accuracy: 0.9971 - val_loss: 3.5647e-05 - val_accuracy: 1.0000
Epoch 3/20
22/22 [==============================] - 0s 4ms/step - loss: 0.0445 - accuracy: 0.9971 - val_loss: 1.8745e-05 - val_accuracy: 1.0000
Epoch 4/20
22/22 [==============================] - 0s 4ms/step - loss: 0.0360 - accuracy: 0.9971 - val_loss: 2.4701e-05 - val_accuracy: 1.0000
Epoch 5/20
22/22 [==============================] - 0s 5ms/step - loss: 0.0282 - accuracy: 0.9971 - val_loss: 1.7195e-05 - val_accuracy: 1.0000
Epoch 6/20
22/22 [==============================] - 0s 4ms/step - loss: 0.0220 - accuracy: 0.9971 - val_loss: 2.0074e-05 - val_accuracy: 1.0000
Epoch 7/20
22/22 [==============================] - 0s 4ms/step - loss: 0.0172 - accuracy: 0.9971 - val_loss: 1.6469e-05 - val_accuracy

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)

10/10 [==============================] - 0s 2ms/step - loss: 1.6469e-05 - accuracy: 1.0000


In [ ]:
print(loss,accuracy)

1.6469160982524045e-05 1.0


In [ ]:
X_train[1,:]

array([ 1.27601202,  0.84205971, -0.78719325,  0.27114709,  0.0914432 ,
       -1.15225119, -0.17499303, -0.75595877,  0.21606328,  1.26932758,
       -0.6264684 , -0.32966841,  1.15083945,  0.58754543, -0.46732349,
       -0.40400292, -0.43372151,  0.76631506, -1.33749671, -0.07386242,
        0.13385722, -0.1880557 , -0.21485977,  0.257486  ,  0.83145499,
       -0.26054154,  1.88262455, -0.13590794,  0.19690083,  0.24717852])

In [ ]:
model.predict([[ 1.27601202,  0.84205971, -0.78719325,  0.27114709,  0.0914432 ,-1.15225119, -0.17499303, -0.75595877,  0.21606328,  1.26932758,-0.6264684 , -0.32966841,  1.15083945,  0.58754543, -0.46732349,-0.40400292, -0.43372151,  0.76631506, -1.33749671, -0.07386242,0.13385722, -0.1880557 , -0.21485977,0.257486,  0.83145499,-0.26054154,  1.88262455, -0.13590794,  0.19690083,  0.24717852]])

1/1 [==============================] - 0s 111ms/step


array([[0.00028154]], dtype=float32)

In [ ]:
prediction=model.predict([[ 5.32000000e+02, -2.08126385e+00,  1.68255833e+00,  6.51263800e-01,-5.33548658e-01,  4.40529215e-01, -1.13732360e-01,  8.75113877e-01,-1.49852238e-01,  1.07760307e+00,  2.23030122e+00,  1.72446870e+00,3.11639406e-01, -2.52562578e-01, -1.10190255e+00,  7.06008442e-01,1.21038721e-01, -3.56188625e-01, -1.25557801e-01, -2.03581005e-01,9.37684099e-01, -5.98398393e-01, -6.25481591e-01,  1.00454588e-01,-3.89908592e-01,  1.33481255e-01,  9.05847152e-02,  6.57235700e-01,2.31941417e-01,  1.79900000e+01]])

1/1 [==============================] - 0s 37ms/step


In [ ]:
print(prediction)

[[0.]]
